const mockData = [
  {
    id: 1,
    name: "Wireless Headphones",
    price: 79.99,
    rating: 4.5,
    loc: "Hanoi",
    status: "Yêu thích",
    note: ["rẻ vô địch", "mua kèm deal sốc", "giam 10k"],
    discount: 15,
    bestSeller: 1745,
    description:
      "High-quality wireless headphones with noise-cancelling feature, comfortable ear pads, and 30-hour battery life.",
    image:
      "https://vn.jbl.com/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw4cd4cad7/JBL_TOUR_ONE_BLK_Hero.png?sw=537&sfrm=png",
    category: "Audio",
    lastUpdated: "2025-03-08",
  },
  {
    id: 2,
    name: "Bluetooth Speaker",
    price: 59.99,
    rating: 4.2,
    loc: "Hanoi",
    status: "Yêu thích",
    discount: 45,
    bestSeller: 46,
    note: ["rẻ vô địch", "mua kèm deal sốc"],
    description:
      "Portable Bluetooth speaker with clear sound quality and 12 hours of playtime, perfect for outdoor use.",
    image:
      "https://vn.jbl.com/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw68adc84b/JBL_CLIP_5_HERO_SAND_49709_x3.png?sw=537&sfrm=png",
    category: "Audio",
    lastUpdated: "2025-02-20",
  },
  {
    id: 3,
    name: "Smartphone Stand",
    price: 19.99,
    rating: 4.8,
    loc: "Hanoi",
    status: "Yêu thích",
    discount: 45,
    bestSeller: 200,
    note: ["rẻ vô địch", "mua kèm deal sốc"],
    description:
      "Adjustable smartphone stand with sturdy base, ideal for video calls, watching movies, or reading.",
    image:
      "https://img.lazcdn.com/g/p/61818973309accaf9b7eb9113e1da64a.jpg_720x720q80.jpg_.webp",
    category: "Accessories",
    lastUpdated: "2025-03-01",
  },
  {
    id: 4,
    name: "LED Desk Lamp",
    price: 39.99,
    rating: 4.6,
    loc: "Hanoi",
    bestSeller: 5789,
    discount: 45,
    status: "Yêu thích",
    note: ["rẻ vô địch", "mua kèm deal sốc"],
    description:
      "Energy-efficient LED desk lamp with adjustable brightness and color temperature, perfect for home office use.",
    image:
      "https://rangdong.com.vn/uploads/product/LED/LED_Den_ban/RD_RL_16_LED/RD_RL_16_LED_0.jpg",
    category: "Home & Office",
    lastUpdated: "2025-03-03",
  },
  {
    id: 5,
    name: "Fitness Tracker Watch",
    price: 129.99,
    rating: 4.7,
    discount: 45,
    loc: "Hanoi",
    bestSeller: 324,
    status: "Yêu thích",
    note: ["rẻ vô địch", "mua kèm deal sốc"],
    description:
      "A sleek fitness tracker with heart rate monitor, sleep tracking, step counting, and waterproof design.",
    image:
      "https://platform.theverge.com/wp-content/uploads/sites/2/2025/02/257523_Amazfit_Active_2_AKrales_0106.jpg?quality=90&strip=all&crop=0%2C0%2C100%2C100&w=2400",
    category: "Wearables",
    lastUpdated: "2025-01-25",
  },
  {
    id: 6,
    name: "Portable Power Bank",
    price: 25.99,
    rating: 4.4,
    discount: 45,
    bestSeller: 567678,
    loc: "Hanoi",
    status: "Yêu thích",
    note: ["rẻ vô địch", "mua kèm deal sốc"],
    description:
      "Compact power bank with 10,000mAh capacity, fast charging capabilities, and dual USB ports.",
    image:
      "https://i0.wp.com/akia.vn/wp-content/uploads/2024/05/tram-sac-du-phong-ugreen-gs1200-1200w.jpg?fit=510%2C510&ssl=1",
    category: "Accessories",
    lastUpdated: "2025-02-10",
  },
  {
    id: 7,
    name: "Laptop Sleeve",
    price: 29.99,
    rating: 4.3,
    discount: 45,
    bestSeller: 3425,
    loc: "Hanoi",
    status: "Yêu thích",
    note: ["rẻ vô địch", "mua kèm deal sốc"],
    description:
      "Stylish and protective laptop sleeve with water-resistant fabric and a soft interior lining to protect your device.",
    image: "https://macinsta.vn/wp-content/uploads/2020/09/MC10-3-510x510.jpg",
    category: "Accessories",
    lastUpdated: "2025-03-08",
  },
  {
    id: 8,
    name: "Smart Thermostat",
    price: 149.99,
    rating: 4.9,
    discount: 45,
    loc: "Hanoi",
    status: "Yêu thích",
    bestSeller: 790,
    note: ["rẻ vô địch", "mua kèm deal sốc"],
    description:
      "Smart thermostat with remote control, energy-saving features, and easy installation.",
    image:
      "https://cdn.thewirecutter.com/wp-content/media/2022/11/smartthermostats-2048px-2898-2x1-1.jpg?width=1024&quality=75&crop=2:1&auto=webp 1x, https://cdn.thewirecutter.com/wp-content/media/2022/11/smartthermostats-2048px-2898-2x1-1.jpg?width=2048&quality=75&crop=2:1&auto=webp 1.1x",
    category: "Home Automation",
    lastUpdated: "2025-03-02",
  },
  {
    id: 9,
    name: "Electric Toothbrush",
    price: 69.99,
    rating: 4.7,
    loc: "Hanoi",
    bestSeller: 124,
    discount: 45,
    note: ["rẻ vô địch", "mua kèm deal sốc"],
    status: "",
    description:
      "Powerful electric toothbrush with multiple brushing modes and a 2-minute timer for thorough cleaning.",
    image:
      "//s.alicdn.com/@sc04/kf/Had4f7fdbd6434adf8da0f878e765c052V.jpg_300x300.jpg",
    category: "Personal Care",
    lastUpdated: "2025-03-03",
  },
  {
    id: 10,
    name: "Gaming Mouse",
    price: 49.99,
    rating: 4.6,
    discount: 45,
    loc: "Hanoi",
    status: "Yêu thích",
    bestSeller: 2345,
    note: ["rẻ vô địch", "mua kèm deal sốc"],
    description:
      "Ergonomic gaming mouse with customizable buttons, adjustable DPI, and RGB lighting.",
    image:
      "//product.hstatic.net/200000722513/product/thumbchuot_a405fadb92a34c429c3eed4d11a84fb5_grande.jpg",
    category: "Accessories",
    lastUpdated: "2025-02-15",
  },
  {
    id: 11,
    name: "Mechanical Keyboard",
    price: 89.99,
    rating: 4.8,
    loc: "Hanoi",
    status: "Yêu thích",
    discount: 20,
    bestSeller: 5321,
    note: ["rẻ vô địch", "mua kèm deal sốc"],
    description:
      "High-performance mechanical keyboard with customizable RGB lighting and durable switches.",
    image:
      "//mechanicalkeyboards.com/cdn/shop/files/18305-9HNJ1-Keychron-Q6-Max.jpg?v=1709587234&width=750",
    category: "Accessories",
    lastUpdated: "2025-03-10",
  },
  {
    id: 12,
    name: "Smartwatch",
    price: 199.99,
    rating: 4.7,
    loc: "Hanoi",
    status: "Yêu thích",
    discount: 30,
    bestSeller: 978,
    note: ["rẻ vô địch", "mua kèm deal sốc"],
    description:
      "Advanced smartwatch with heart rate monitoring, GPS tracking, and long battery life.",
    image:
      "https://cdnv2.tgdd.vn/mwg-static/tgdd/Products/Images/7077/333790/kidcare-sight-s1-xanh-hc-1-638727316855316686-750x500.jpg",
    category: "Wearables",
    lastUpdated: "2025-03-09",
  },
  {
    id: 13,
    name: "Wireless Charging Pad",
    price: 34.99,
    rating: 4.5,
    loc: "Hanoi",
    status: "Yêu thích",
    discount: 25,
    bestSeller: 456,
    note: ["rẻ vô địch", "mua kèm deal sốc"],
    description:
      "Fast wireless charging pad compatible with various smartphone models and smart devices.",
    image:
      "https://down-vn.img.susercontent.com/file/vn-11134258-7ra0g-m6xq0p3e3uqvb5",
    category: "Accessories",
    lastUpdated: "2025-03-08",
  },
  {
    id: 14,
    name: "Noise-Cancelling Earbuds",
    price: 129.99,
    rating: 4.6,
    loc: "Hanoi",
    status: "Yêu thích",
    discount: 40,
    bestSeller: 3156,
    note: ["rẻ vô địch", "mua kèm deal sốc"],
    description:
      "Premium noise-cancelling earbuds with superior sound quality and touch controls.",
    image:
      "https://i.rtings.com/assets/products/81R24T2e/jabra-elite-10-true-wireless/design-small.jpg?format=auto",
    category: "Audio",
    lastUpdated: "2025-03-07",
  },
  {
    id: 15,
    name: "Smart Light Bulb",
    price: 19.99,
    rating: 4.4,
    loc: "Hanoi",
    status: "Yêu thích",
    discount: 35,
    bestSeller: 2432,
    note: ["rẻ vô địch", "mua kèm deal sốc"],
    description:
      "Color-changing smart light bulb with voice control and energy-efficient design.",
    image: "https://smarthomekit.vn/wp-content/uploads/2022/11/BULB-W4-Yeelight-min-600x600.jpg",
    category: "Home Automation",
    lastUpdated: "2025-03-06",
  },
  {
    id: 16,
    name: "External Hard Drive",
    price: 99.99,
    rating: 4.7,
    loc: "Hanoi",
    status: "Yêu thích",
    discount: 15,
    bestSeller: 1789,
    note: ["rẻ vô địch", "mua kèm deal sốc"],
    description:
      "High-speed external hard drive with 2TB capacity, perfect for data backup and storage.",
    image: "https://seagatevietnam.com/wp-content/uploads/2016/07/expandsion2tb-800x800.webp",
    category: "Storage",
    lastUpdated: "2025-03-05",
  },
  {
    id: 17,
    name: "Ergonomic Office Chair",
    price: 259.99,
    rating: 4.8,
    loc: "Hanoi",
    status: "Yêu thích",
    discount: 20,
    bestSeller: 652,
    note: ["rẻ vô địch", "mua kèm deal sốc"],
    description:
      "Comfortable ergonomic office chair with lumbar support and adjustable height.",
    image: "//product.hstatic.net/1000213518/product/t21_23e260f679b44919a522f434815dcd71_master.jpg",
    category: "Home & Office",
    lastUpdated: "2025-03-04",
  },
  {
    id: 18,
    name: "Smart Door Lock",
    price: 189.99,
    rating: 4.9,
    loc: "Hanoi",
    status: "Yêu thích",
    discount: 30,
    bestSeller: 932,
    note: ["rẻ vô địch", "mua kèm deal sốc"],
    description:
      "Secure smart door lock with fingerprint recognition and mobile app control.",
    image:
      "https://i0.wp.com/cannhacongnghe.com/wp-content/uploads/2022/04/xiaomi-lockin-smart-lock-x1-1.jpg?fit=510%2C510&ssl=1",
    category: "Home Automation",
    lastUpdated: "2025-03-03",
  },
  {
    id: 19,
    name: "Drone Camera",
    price: 499.99,
    rating: 4.8,
    loc: "Hanoi",
    status: "Yêu thích",
    discount: 50,
    bestSeller: 321,
    note: ["rẻ vô địch", "mua kèm deal sốc"],
    description:
      "High-resolution drone camera with real-time transmission and long battery life.",
    image:
      "https://dji-vietnam.vn/wp-content/uploads/2021/01/flycam-2.jpg",
    category: "Gadgets",
    lastUpdated: "2025-03-02",
  },
  {
    id: 20,
    name: "Robot Vacuum Cleaner",
    price: 349.99,
    rating: 4.7,
    loc: "Hanoi",
    status: "Yêu thích",
    discount: 40,
    bestSeller: 1124,
    note: ["rẻ vô địch", "mua kèm deal sốc"],
    description:
      "Smart robot vacuum cleaner with automatic scheduling, powerful suction, and app control.",
    image:
      "https://mivietnam.vn/wp-content/uploads/2023/05/mivietnam-robot-hut-bui-xiaomi-vauum-x20-plus-01.jpg",
    category: "Home Automation",
    lastUpdated: "2025-03-01",
  },
];
export default mockData;
